In [1]:
import torch
print(torch.__version__)

2.11.0+cu130


In [2]:
if torch.cuda.is_available():
  print('GPU available')
  print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
  print('GPU not available, using CPU')

GPU available
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
# Using empty
a = torch.empty(2,3)

In [5]:
# Check type
type(a)

torch.Tensor

In [8]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# Using rand
torch.rand(2,3)

tensor([[0.0477, 0.8718, 0.9688],
        [0.7744, 0.2136, 0.5622]])

In [14]:
# Use of seed
torch.rand(2,3)


tensor([[0.0552, 0.6890, 0.3105],
        [0.2331, 0.3831, 0.6873]])

In [16]:
# Manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
# Other ways

# arange
print('using arange ->',torch.arange(0,10))
print('using arange ->',torch.arange(0,10,2))

# linspace
print('using linspace ->',torch.linspace(0,10,10))

# eye
print('using eye ->',torch.eye(5))

# full
print('using full ->',torch.full((3,3), 5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [26]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [29]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068371993545223478, 3545241344705966130],
        [6499035343654041134, 7309453675965983778, 8315168162784306286]])

In [30]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [40]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [35]:
# Find data type
x.dtype

torch.int64

In [36]:
# Assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
torch.tensor([1,2,3],dtype = torch.float32)

tensor([1., 2., 3.])

In [38]:
# Using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

## 1.Scalar operations

In [42]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [50]:
# addition
x + 2

# substraction
x - 2

# multiplication
x * 3

# division
x / 3

# int division
(x * 100) // 3

# mod
((x * 100) // 3) % 2

# power
x ** 2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

## 2.Element wise operations

In [51]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [59]:
# addition
a + b

# substraction
a - b

# multiplication
a * b

# division
a / b

# mod
a % b

# power
a ** b

tensor([[0.2771, 0.9096, 0.8672],
        [0.9839, 0.6515, 0.9868]])

In [60]:
c = torch.tensor([1,-2,3,-4])

In [62]:
# abs
torch.abs(c)

# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [63]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [69]:
# round
torch.round(d)

# ceil
torch.ceil(d)

# floor
torch.floor(d)

# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3.Reduction operations

In [77]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
print(e)

tensor([[7., 9., 2.],
        [6., 7., 7.]])


In [89]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e,dim = 0)

# sum along rws
torch.sum(e,dim = 1)

# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

# median
torch.median(e)

# max and min
torch.max(e)
torch.min(e)

# product
torch.prod(e)

# standard deviation
torch.std(e)

# variance
torch.var(e)

# argmax
torch.argmax(e)

# argmin
torch.argmin(e)

tensor(2)

## 4.Matrix operations

In [90]:
f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g = torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)
print(f)
print(g)

tensor([[8., 3., 6.],
        [1., 5., 5.]])
tensor([[0., 4.],
        [3., 8.],
        [8., 3.]])


In [91]:
# Matrix Multiplication

torch.matmul(f,g)

tensor([[57., 74.],
        [55., 59.]])

In [92]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [94]:
f

tensor([[8., 3., 6.],
        [1., 5., 5.]])

In [93]:
# transpose
torch.transpose(f,0,1)

tensor([[8., 1.],
        [3., 5.],
        [6., 5.]])

In [95]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 5., 0.],
        [6., 4., 0.],
        [8., 4., 7.]])

In [96]:
# determinant
torch.det(h)

tensor(-126.)

In [97]:
# inverse
torch.inverse(h)

tensor([[-2.2222e-01,  2.7778e-01,  7.4506e-09],
        [ 3.3333e-01, -1.6667e-01, -6.3862e-09],
        [ 6.3492e-02, -2.2222e-01,  1.4286e-01]])

## 5.Comparison operations

In [98]:
i = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
j = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

print(i)
print(j)

tensor([[2., 3., 8.],
        [5., 6., 2.]])
tensor([[9., 5., 0.],
        [4., 2., 7.]])


In [104]:
# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

# greater than equal to
i >= j

# less than equal to
i <= j


tensor([[ True,  True, False],
        [False, False,  True]])

## 6.Special functions

In [105]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 1., 5.],
        [4., 4., 1.]])

In [106]:
# log
torch.log(k)

tensor([[0.0000, 0.0000, 1.6094],
        [1.3863, 1.3863, 0.0000]])

In [107]:
# exp
torch.exp(k)

tensor([[  2.7183,   2.7183, 148.4132],
        [ 54.5981,  54.5981,   2.7183]])

In [108]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 1.0000, 2.2361],
        [2.0000, 2.0000, 1.0000]])

In [109]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.7311, 0.9933],
        [0.9820, 0.9820, 0.7311]])

In [110]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.0474, 0.9820],
        [0.9526, 0.9526, 0.0180]])

In [111]:
# relu
torch.relu(k)

tensor([[1., 1., 5.],
        [4., 4., 1.]])

# Inplace Operations

In [112]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])
tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])


In [113]:
m.add_(n)

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [114]:
m

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [115]:
n

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [116]:
torch.relu(m)

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [117]:
m.relu_()

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [118]:
m

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

# Copying a Tensor

In [120]:
a = torch.rand(2,3)
a

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [122]:
b = a
b

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [123]:
a[0][0] = 0
print(a)
print(b)

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])
tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])


In [124]:
id(a)

138158917825984

In [125]:
id(b)

138158917825984

In [126]:
b = a.clone()

In [127]:
a[0][0] = 10
print(a)
print(b)

tensor([[10.0000,  0.8497,  0.9112],
        [ 0.4847,  0.9436,  0.3904]])
tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])


In [128]:
id(a)

138158917825984

In [129]:
id(b)

138158916199168

# Tensor Operations on GPU

In [131]:
torch.cuda.is_available()

True

In [132]:
device = torch.device('cuda')

In [133]:
# Creating a new tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [137]:
# Moving an existing tensor to GPU
print(a)

b = a.to(device)

print(b)

tensor([[10.0000,  0.8497,  0.9112],
        [ 0.4847,  0.9436,  0.3904]])
tensor([[10.0000,  0.8497,  0.9112],
        [ 0.4847,  0.9436,  0.3904]], device='cuda:0')


In [138]:
b + 5

tensor([[15.0000,  5.8497,  5.9112],
        [ 5.4847,  5.9436,  5.3904]], device='cuda:0')

In [140]:
import torch
import time


# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")


# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")


# Compare results
print('\nSppedup (CPU time / GPU time): ',cpu_time/gpu_time)

Time on CPU: 16.4909 seconds
Time on GPU: 0.5954 seconds

Sppedup (CPU time / GPU time):  27.696589098987484


# Reshaping Tensors

In [141]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [142]:
# Reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [144]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [145]:
b = torch.rand(2,3,4)
b

tensor([[[0.1008, 0.1176, 0.3651, 0.4549],
         [0.8776, 0.3721, 0.7827, 0.4926],
         [0.7323, 0.4682, 0.4369, 0.3151]],

        [[0.6987, 0.7903, 0.5187, 0.7766],
         [0.9718, 0.5460, 0.9329, 0.9847],
         [0.6817, 0.2420, 0.6212, 0.0121]]])

In [146]:
# Permute
b.permute(2,0,1)    # Dimensions change:  (2,3,4) -> (4,2,3)

tensor([[[0.1008, 0.8776, 0.7323],
         [0.6987, 0.9718, 0.6817]],

        [[0.1176, 0.3721, 0.4682],
         [0.7903, 0.5460, 0.2420]],

        [[0.3651, 0.7827, 0.4369],
         [0.5187, 0.9329, 0.6212]],

        [[0.4549, 0.4926, 0.3151],
         [0.7766, 0.9847, 0.0121]]])

In [147]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [149]:
# Unsqueeze
c = torch.rand(226,226,3)    # Typical image size
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [150]:
# Squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [151]:
import numpy as np

In [152]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [154]:
b = a.numpy()
b

array([1, 2, 3])

In [155]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [156]:
torch.from_numpy(c)

tensor([1, 2, 3])